server:
  port: 2204
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:mysql://localhost:3306/con_wall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: zhangjie
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



mybatis-plus:

  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  # 搜索指定包别名
  typeAliasesPackage: com.confession.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wechat:
  app-id: wxade44f34c116d260
  app-secret: 28e18de4781d84bd1badab528cf736a6
  msgDataFormat: JSON


wall:
  admin:
    daily-post-limit: 10 #墙每天投稿上限数量
  user:
    daily-post-limit: 3
    comment-limit: 3  #每天评论数量限制
  lottery:   #恋爱墙投递和读取配置   只能选择一个  投递和拿的限制都是一样的
    strategy: ONCE    # YEARLY, MONTHLY, DAILY, ONCE 其中之一  ONCE是一共只能放的
    limit:    #次数限制
      daily: 2     #天次数
      yearly: 2   #年次数
      monthly: 3   #月次数
      total: 3   #总次数


